# Build CloudStream plugins and push artifacts to the `builds` branch

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    # make sure the workflow can push to the repo
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Check Java version
        run: java -version

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Clean old builds
        run: rm "$GITHUB_WORKSPACE/builds/"*.cs3 || true

      - name: Build plugins
        run: |
          cd "$GITHUB_WORKSPACE/src"
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 "$GITHUB_WORKSPACE/builds" || true
          cp build/plugins.json "$GITHUB_WORKSPACE/builds"

      - name: Push builds
        run: |
          cd "$GITHUB_WORKSPACE/builds"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
